#!/usr/bin/env python3
"""Merge batch-1 authoring chunks into final paths.

- Renumbers eval items from chunks to contiguous Q016+ and appends to eval/questions.yaml
- Concats SFT JSONL chunks into data/sft/qa_train.jsonl
- Concats DPO-bulk chunks into data/dpo/bulk_train.jsonl
- Copies curated DPO chunk to data/dpo/curated_train.jsonl
- Derives RL prompts from factoid eval (with traps -> must_not_contain) and factoid SFT (empty must_not_contain)
"""
from __future__ import annotations
import json
import shutil
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
SYS = "你是罗德岛的档案管理员。基于公开档案准确回答关于泰拉世界的问题；不确定时坦诚说明。"


def load_jsonl(p: Path) -> list[dict]:
    rows: list[dict] = []
    for line in p.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if line:
            rows.append(json.loads(line))
    return rows


def write_jsonl(p: Path, rows: list[dict]) -> None:
    with p.open("w", encoding="utf-8") as f:
        for r in rows:
            f.write(json.dumps(r, ensure_ascii=False) + "\n")


def concat_jsonl(chunks: list[Path], out: Path) -> int:
    rows: list[dict] = []
    for c in chunks:
        rows.extend(load_jsonl(c))
    write_jsonl(out, rows)
    return len(rows)


def main() -> None:
    # ---- 1. Eval chunks -> append to questions.yaml with renumbering -----
    eval_chunks = [
        ROOT / "data_gen/_chunks/eval_chars_A.yaml",
        ROOT / "data_gen/_chunks/eval_events_B.yaml",
        ROOT / "data_gen/_chunks/eval_refusal_C.yaml",
    ]
    new_items: list[dict] = []
    for c in eval_chunks:
        data = yaml.safe_load(c.read_text(encoding="utf-8"))
        if not isinstance(data, list):
            raise SystemExit(f"{c}: top-level YAML must be a list (got {type(data).__name__})")
        new_items.extend(data)

    start_id = 16
    for i, item in enumerate(new_items, start=start_id):
        item["id"] = f"Q{i:03d}"
    end_id = start_id + len(new_items) - 1

    qfile = ROOT / "eval/questions.yaml"
    existing = qfile.read_text(encoding="utf-8")
    header = (
        f"\n"
        f"# =============================================================================\n"
        f"# Batch 1 (KB-grounded): Q{start_id:03d}-Q{end_id:03d}\n"
        f"#   - chars (8 ops: kalts/amiya/texas/exusiai/lappland/svrash/chen/w)\n"
        f"#   - events (main_0/5/7/8/10/11) + world + faction\n"
        f"#   - refusal items (50 across 7 buckets)\n"
        f"# Generated by data_gen/merge_batch1.py\n"
        f"# =============================================================================\n\n"
    )
    appended = yaml.dump(
        new_items, allow_unicode=True, sort_keys=False, width=120, default_flow_style=False
    )
    if not existing.endswith("\n"):
        existing += "\n"
    qfile.write_text(existing + header + appended, encoding="utf-8")
    print(f"eval: appended {len(new_items)} items as Q{start_id:03d}-Q{end_id:03d} -> {qfile.relative_to(ROOT)}")

    # ---- 2. SFT JSONL ----
    sft_chunks = [ROOT / "data/sft/_chunks/chars_A.jsonl", ROOT / "data/sft/_chunks/events_B.jsonl"]
    sft_out = ROOT / "data/sft/qa_train.jsonl"
    n_sft = concat_jsonl(sft_chunks, sft_out)
    print(f"sft : {n_sft} pairs -> {sft_out.relative_to(ROOT)}")

    # ---- 3. DPO bulk ----
    dpo_chunks = [ROOT / "data/dpo/_chunks/bulk_chars_A.jsonl", ROOT / "data/dpo/_chunks/bulk_events_B.jsonl"]
    dpo_out = ROOT / "data/dpo/bulk_train.jsonl"
    n_dpo = concat_jsonl(dpo_chunks, dpo_out)
    print(f"dpo : {n_dpo} bulk pairs -> {dpo_out.relative_to(ROOT)}")

    # ---- 4. DPO curated ----
    curated_in = ROOT / "data/dpo/_chunks/curated_C.jsonl"
    curated_out = ROOT / "data/dpo/curated_train.jsonl"
    shutil.copyfile(curated_in, curated_out)
    n_cur = len(load_jsonl(curated_out))
    print(f"dpo : {n_cur} curated pairs -> {curated_out.relative_to(ROOT)}")

    # ---- 5. RL prompts ----
    # (a) factoid eval items: keep traps as must_not_contain (these are gold-curated trap strings)
    # (b) factoid SFT rows:   empty must_not_contain (no curated trap signal — enrichment for later batches)
    rl_rows: list[dict] = []
    rl_id = 1

    for item in new_items:
        if item.get("answer_type") != "factoid":
            continue
        rl_rows.append({
            "id": f"RL{rl_id:05d}",
            "prompt": [
                {"role": "system", "content": SYS},
                {"role": "user", "content": item["question_zh"]},
            ],
            "key_facts": item.get("key_facts", []),
            "must_not_contain": item.get("traps", []),
            "category": item["category"],
            "answer_type": "factoid",
            "source": item.get("source", ""),
        })
        rl_id += 1

    sft_rows = load_jsonl(sft_out)
    for row in sft_rows:
        if row.get("answer_type") != "factoid":
            continue
        rl_rows.append({
            "id": f"RL{rl_id:05d}",
            "prompt": [m for m in row["messages"] if m["role"] != "assistant"],
            "key_facts": row.get("key_facts", []),
            "must_not_contain": [],
            "category": row.get("category", "character"),
            "answer_type": "factoid",
            "source": row.get("source", ""),
        })
        rl_id += 1

    rl_out = ROOT / "data/rl/prompts_train.jsonl"
    write_jsonl(rl_out, rl_rows)
    print(f"rl  : {len(rl_rows)} prompts -> {rl_out.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
