#!/usr/bin/env python3
"""Merge subsequent authoring batches (after batch 1) into final paths.

Usage:
    python3 data_gen/merge_batch.py D E F

Behavior:
- For each batch letter L, finds chunk files in data_gen/_chunks/ and data/{sft,dpo}/_chunks/:
    * data_gen/_chunks/eval_*_L.yaml   -> append to eval/questions.yaml (renumbered)
    * data/sft/_chunks/*_L.jsonl       -> append to data/sft/qa_train.jsonl
    * data/dpo/_chunks/bulk_*_L.jsonl  -> append to data/dpo/bulk_train.jsonl
    * data/dpo/_chunks/curated_*_L.jsonl -> append to data/dpo/curated_train.jsonl
- Eval items are renumbered contiguously starting from max(Q-id in questions.yaml) + 1
- RL prompts are REGENERATED from scratch using the full updated eval + full SFT (factoid only).
"""
from __future__ import annotations

import argparse
import json
import re
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
SYS = "你是罗德岛的档案管理员。基于公开档案准确回答关于泰拉世界的问题；不确定时坦诚说明。"
ID_RE = re.compile(r"^Q(\d{3})$")


def load_jsonl(p: Path) -> list[dict]:
    if not p.exists():
        return []
    rows: list[dict] = []
    for line in p.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if line:
            rows.append(json.loads(line))
    return rows


def write_jsonl(p: Path, rows: list[dict]) -> None:
    p.parent.mkdir(parents=True, exist_ok=True)
    with p.open("w", encoding="utf-8") as f:
        for r in rows:
            f.write(json.dumps(r, ensure_ascii=False) + "\n")


def append_jsonl(p: Path, rows: list[dict]) -> None:
    p.parent.mkdir(parents=True, exist_ok=True)
    with p.open("a", encoding="utf-8") as f:
        for r in rows:
            f.write(json.dumps(r, ensure_ascii=False) + "\n")


def current_max_qid(qfile: Path) -> int:
    items = yaml.safe_load(qfile.read_text(encoding="utf-8")) or []
    max_n = 0
    for it in items:
        m = ID_RE.match(it.get("id", "") if isinstance(it, dict) else "")
        if m:
            max_n = max(max_n, int(m.group(1)))
    return max_n


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("batches", nargs="+", help="Batch letters (e.g. D E F)")
    args = ap.parse_args()

    qfile = ROOT / "eval/questions.yaml"
    eval_dir = ROOT / "data_gen/_chunks"
    sft_dir = ROOT / "data/sft/_chunks"
    dpo_dir = ROOT / "data/dpo/_chunks"

    start_id = current_max_qid(qfile) + 1
    cur_id = start_id

    # ---- 1. Eval ----
    new_eval: list[dict] = []
    for letter in args.batches:
        for p in sorted(eval_dir.glob(f"eval_*_{letter}.yaml")):
            items = yaml.safe_load(p.read_text(encoding="utf-8"))
            if not isinstance(items, list):
                raise SystemExit(f"{p}: top-level must be list")
            for it in items:
                it["id"] = f"Q{cur_id:03d}"
                cur_id += 1
                new_eval.append(it)
            print(f"eval: loaded {len(items):3d} items from {p.name}")

    if new_eval:
        existing = qfile.read_text(encoding="utf-8")
        end_id = cur_id - 1
        header = (
            f"\n# =============================================================================\n"
            f"# Batches {','.join(args.batches)}: Q{start_id:03d}-Q{end_id:03d} "
            f"({len(new_eval)} items)\n"
            f"# Generated by data_gen/merge_batch.py\n"
            f"# =============================================================================\n\n"
        )
        appended = yaml.dump(
            new_eval, allow_unicode=True, sort_keys=False, width=120, default_flow_style=False
        )
        if not existing.endswith("\n"):
            existing += "\n"
        qfile.write_text(existing + header + appended, encoding="utf-8")
        print(f"eval: appended {len(new_eval)} items as Q{start_id:03d}-Q{end_id:03d}")

    # ---- 2. SFT ----
    sft_out = ROOT / "data/sft/qa_train.jsonl"
    sft_added = 0
    for letter in args.batches:
        for p in sorted(sft_dir.glob(f"*_{letter}.jsonl")):
            rows = load_jsonl(p)
            append_jsonl(sft_out, rows)
            sft_added += len(rows)
            print(f"sft : appended {len(rows):3d} from {p.name}")

    # ---- 3. DPO bulk ----
    dpo_bulk_out = ROOT / "data/dpo/bulk_train.jsonl"
    dpo_added = 0
    for letter in args.batches:
        for p in sorted(dpo_dir.glob(f"bulk_*_{letter}.jsonl")):
            rows = load_jsonl(p)
            append_jsonl(dpo_bulk_out, rows)
            dpo_added += len(rows)
            print(f"dpo : appended {len(rows):3d} bulk from {p.name}")

    # ---- 4. DPO curated ----
    cur_out = ROOT / "data/dpo/curated_train.jsonl"
    cur_added = 0
    for letter in args.batches:
        for p in sorted(dpo_dir.glob(f"curated_*_{letter}.jsonl")):
            rows = load_jsonl(p)
            append_jsonl(cur_out, rows)
            cur_added += len(rows)
            print(f"dpo : appended {len(rows):3d} curated from {p.name}")

    # ---- 5. RL prompts (regenerated fresh from FULL eval + FULL SFT) ----
    all_eval = yaml.safe_load(qfile.read_text(encoding="utf-8")) or []
    all_sft = load_jsonl(sft_out)
    rl_rows: list[dict] = []
    rl_id = 1

    for it in all_eval:
        if it.get("answer_type") != "factoid":
            continue
        rl_rows.append({
            "id": f"RL{rl_id:05d}",
            "prompt": [
                {"role": "system", "content": SYS},
                {"role": "user", "content": it["question_zh"]},
            ],
            "key_facts": it.get("key_facts", []),
            "must_not_contain": it.get("traps", []),
            "category": it["category"],
            "answer_type": "factoid",
            "source": it.get("source", ""),
        })
        rl_id += 1

    for row in all_sft:
        if row.get("answer_type") != "factoid":
            continue
        rl_rows.append({
            "id": f"RL{rl_id:05d}",
            "prompt": [m for m in row["messages"] if m["role"] != "assistant"],
            "key_facts": row.get("key_facts", []),
            "must_not_contain": [],
            "category": row.get("category", "character"),
            "answer_type": "factoid",
            "source": row.get("source", ""),
        })
        rl_id += 1

    rl_out = ROOT / "data/rl/prompts_train.jsonl"
    write_jsonl(rl_out, rl_rows)
    print(f"rl  : regenerated {len(rl_rows)} prompts -> {rl_out.relative_to(ROOT)}")

    print("\n=== Summary ===")
    print(f"eval items added : {len(new_eval)}")
    print(f"sft  pairs added : {sft_added}")
    print(f"dpo  bulk added  : {dpo_added}")
    print(f"dpo  curated +   : {cur_added}")
    print(f"rl prompts (total): {len(rl_rows)}")


if __name__ == "__main__":
    main()
